server:
  port: 5632

  spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/TestSpring?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&&zeroDateTimeBehavior=convertToNull
      username: root
      password: root

#mybatis-plush配置
mybatis-plus:
  #  配置查询数据的封装对象
  type-aliases-package: com.xyk.pojo
  #  配置自定义sql语句
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        #      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.xyk: info


#springboot 集成 Knife4j报错时配置(第一步,添加三个依赖;第二步:添加配置类,修改其中的controller包路径,第三步:如果报错就在yml中添加以下配置)
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
